---
name: Publish PowerShell Module
on:
  release:
    types: [created]
jobs:
  Publish-to-Gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        PSGalleryToken: ${{ secrets.PSGalleryToken }}
      shell: pwsh
      run: |
        Publish-Module -Path 'CCMLogs' -NuGetApiKey $env:PSGalleryToken -Verbose
...